name: Android

on:
  push:
    branches: [ "github_action" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Environment
        uses: ./.github/workflows/setup

      - run: flutter test
      - run: flutter build apk --debug
      - run: flutter build appbundle --debug
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          # Try running the build locally with the build command to be sure of this path
          path: build/app/outputs/flutter-apk/app-debug.apk
      - name: Archive Bundle
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          # Try running the build locally with the build command to be sure of this path
          path: build/app/outputs/bundle/debug/app-debug.aab
