# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "github_action" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Environment
        uses: ./.github/workflows/setup_env.yml

      - run: flutter test
      - run: flutter build apk --debug
      - run: flutter build appbundle --debug
      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          # Try running the build locally with the build command to be sure of this path
          path: build/app/outputs/flutter-apk/app-debug.apk
      - name: Archive Bundle
        uses: actions/upload-artifact@v2
        with:
          name: release-bundle
          # Try running the build locally with the build command to be sure of this path
          path: build/app/outputs/bundle/debug/app-debug.aab

  build_mac:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Environment
        uses: ./.github/workflows/setup

      - run: flutter test

      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          # always use --export-options-plist=ios/GithubActionsExportOptions.plist
          build-cmd: flutter build ipa --debug
          certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Archive IPA
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          # Try running the build locally with the build command to be sure of this path
          path: build/ios/ipa/App-dev.ipa