name: Setup Environment

on:
  workflow_call:

jobs:
  setup-environment:
    runs-on: 
      - ubuntu-latest
      - macos-latest
      
    steps:
      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
            channel: stable
            version: 3.24.0

      - run: flutter --version
      - run: flutter pub get
